spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Gera ou atualiza as tabelas automaticamente.
    show-sql: true # Exibe as queries SQL no console.
    open-in-view: true
  application:
    name: registo-horas

# Configuração do Flyway (migrations em src/main/resources/db/migration)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: minhaSuperChaveSecretaComPeloMenos256BitsParaHS256Seguranca
  expiration: 86400000  # 24 horas em millisegundos

  #Configurações do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs  # Endpoint JSON da documentação
  swagger-ui:
    path: /swagger-ui.html  # Endpoint da interface Swagger UI
    enabled: true
    operations-sorter: method  # Ordena por método HTTP
    tags-sorter: alpha  # Ordena tags alfabeticamente
    try-it-out-enabled: true  # Habilita botão "Try it out"
    filter: true  # Habilita filtro de busca
    display-request-duration: true  # Mostra duração das requisições
# Logging para debug
logging:
  level:
    org.springframework.security: DEBUG
    com.registo.horas_estagio: DEBUG
    org.flywaydb: DEBUG