-- DROP TABLE public.usuario;


CREATE TABLE public.usuario (
id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
"password" varchar(255) NOT NULL,
public_id uuid NOT NULL,
"role" varchar(255) NOT NULL,
username varchar(255) NOT NULL,
CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username),
CONSTRAINT uk86bd02ads59gpv1a44lrkjuee UNIQUE (public_id),
CONSTRAINT usuario_pkey PRIMARY KEY (id)
);


CREATE TABLE public.register_horas (
id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
data_fim timestamp(6) NOT NULL,
data_inicio timestamp(6) NOT NULL,
descricao varchar(255) NOT NULL,
estagiario varchar(255) NOT NULL,
horas_trabalhadas float8 NOT NULL,
public_id uuid NOT NULL,
usuario_id int8 NOT NULL,
CONSTRAINT register_horas_pkey PRIMARY KEY (id),
CONSTRAINT uk2ik288kro6htj7d7pux5vgrdi UNIQUE (public_id)
);
-- public.register_horas foreign keys
ALTER TABLE public.register_horas ADD CONSTRAINT fkc9ysqearmo0xi4ul2aqxssfeo FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

-- DROP TABLE public.register_horas;

CREATE TABLE public.jwt_token (
id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
expires_at timestamptz(6) NOT NULL,
issued_at timestamptz(6) NOT NULL,
public_id uuid NOT NULL,
revoked bool NOT NULL,
"token" varchar(2000) NOT NULL,
usuario_id int8 NOT NULL,
CONSTRAINT jwt_token_pkey PRIMARY KEY (id),
CONSTRAINT ukekc1jhsk2cbhnug4fxp4qpovw UNIQUE (public_id)
);
-- public.jwt_token foreign keys

ALTER TABLE public.jwt_token ADD CONSTRAINT fk7cl6n05v5p1q1rjgk58xplqke FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);
