
-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    public_id uuid NOT NULL,
    "password" varchar(255) NOT NULL,
    "role" varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_public_id_key UNIQUE (public_id),
    CONSTRAINT usuario_username_key UNIQUE (username)
);


