-- Drop table

-- DROP TABLE public.register_horas;

CREATE TABLE public.register_horas (
   horas_trabalhadas int4 NOT NULL,
   data_fim timestamp(6) NOT NULL,
   data_inicio timestamp(6) NOT NULL,
   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
   usuario_id int8 NOT NULL,
   public_id uuid NOT NULL,
   descricao varchar(255) NOT NULL,
   estagiario varchar(255) NOT NULL,
   CONSTRAINT register_horas_pkey PRIMARY KEY (id),
   CONSTRAINT register_horas_public_id_key UNIQUE (public_id),
   CONSTRAINT fkc9ysqearmo0xi4ul2aqxssfeo FOREIGN KEY (usuario_id) REFERENCES public.usuario(id)
);

