name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [23]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build (compile + tests)
        run: mvn -B -V clean verify

      - name: Run additional static analysis (optional)
        # Exemplo: se tiver plugins como spotbugs, checkstyle configurados no pom
        run: mvn -B spotbugs:check checkstyle:check || true

      - name: Package artifact
        run: mvn -B -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  optionally-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      # Exemplos de ações de publicação:
      # - publicar imagem Docker para Docker Hub / ghcr
      # - publicar jar para repositório Maven (Nexus, GitHub Packages)
      - name: Example - Build and push Docker image (optional)
        if: env.DOCKER_PUBLISH == 'true'
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t $DOCKERHUB_USER/myapp:${{ github.sha }} .
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/myapp:${{ github.sha }}
