# ... existing code ...
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # USAR a raiz do workspace (evita duplicações)
    strategy:
      matrix:
        java-version: [23]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD: $(pwd)"
          echo "Top-level files:"
          ls -la
          echo "Find pom.xml and mvnw:"
          find . -maxdepth 4 -name pom.xml -o -name mvnw -print || true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Build (compile + tests)
        run: ./mvnw -B -V clean verify

      - name: Package artifact (skip tests)
        run: ./mvnw -B -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Build and push Docker image (optional)
        if: env.DOCKER_PUBLISH == 'true'
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t $DOCKERHUB_USER/registro-horas:${{ github.sha }} .
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/registro-horas:${{ github.sha }}
# ... existing code ...
