# language: yaml
name: Build and publish Docker image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write   # necessário apenas se usar OIDC para autenticação externa

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [23]
    env:
      IMAGE_NAME: horas_estagio
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -B -U clean package

      - name: Set up QEMU (for multi-platform) and Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
          build-args: |
            MAVEN_BUILD=target

      - name: Image info
        run: |
          echo "Image pushed: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}"
