name: Build and push Docker image

on:
  push:
     branches:  [main, master ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [23]
    env:
      IMAGE_NAME: vault-custom
      REGISTRY: docker.io
      PROJECT_DIR: ./horas_estagio
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image tags (debug)
        run: |
          IMAGE_BASE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
          IMAGE_TAG="${IMAGE_BASE}:${{ github.sha }}"
          IMAGE_LATEST="${IMAGE_BASE}:latest"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PROJECT_DIR }}
          file: ${{ env.PROJECT_DIR }}/Dockerfile_vault
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_LATEST }}
          build-args: |
            MAVEN_BUILD=target

      - name: Verify pushed image (list remote tags via Docker Hub API, non-authenticated for public repos)
        run: |
          echo "Attempting to pull the just pushed image to verify..."
          docker pull ${{ env.IMAGE_TAG }} || true
          echo "Local docker images:"
          docker images | head -n 20

      - name: Image info
        run: |
          echo "Image pushed: "${IMAGE_BASE}:${{ github.sha }}""
