name: Build and push Docker image

on:
  push:
    branches: [ main, master  ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [23]
    env:
      IMAGE_NAME: vault-custom
      REGISTRY: docker.io
      PROJECT_DIR: ./horas_estagio
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image tags (debug)
        run: |
          IMAGE_BASE="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
          IMAGE_TAG="${IMAGE_BASE}:${{ github.sha }}"
          IMAGE_LATEST="${IMAGE_BASE}:latest"
          echo "IMAGE_BASE=${IMAGE_BASE}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE_LATEST}" >> $GITHUB_ENV
          echo "Prepared IMAGE_BASE=${IMAGE_BASE}"
          echo "Prepared IMAGE_TAG=${IMAGE_TAG}"
          echo "Prepared IMAGE_LATEST=${IMAGE_LATEST}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Trabalhar na subpasta horas_estagio onde está o pom.xml e o mvnw
      - name: Grant execute permission for mvnw
        working-directory: ${{ env.PROJECT_DIR }}
        run: chmod +x ./mvnw

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PROJECT_DIR }}
          file: ${{ env.PROJECT_DIR }}/Dockerfile_vault
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_LATEST }}
          build-args: |
            MAVEN_BUILD=target

      - name: Verify pushed image (attempt pull)
        run: |
          echo "Attempting to pull the just pushed image to verify..."
          docker pull "${IMAGE_TAG}" || true
          echo "Local docker images:"
          docker images | head -n 20

      - name: Image info
        run: |
          echo "Image pushed: ${IMAGE_BASE}:${{ github.sha }}"
